### ISSUE TITLE
Playlist has lots of songs, but on first load, none listed

### ISSUE THREAD

**Issue by theschles** [gilbarbara/Turntable.fm-Playlists#13]
Version 0.961 of the extension on the latest Chrome public release on OS X 10.6

Screenshot: http://www.flickr.com/photos/66524440@N08/6186015380/

To get the playlist entries, I have to change to a different playlist, then change back to the currently displayed list.

If I happen to drag a song onto the empty list, my entire playlist is replaced by that single song (requiring me to restore).

**Comment by gilbarbara** [comment]
hello again!
Yes this is a known bug.

To keep the Playlists extension simple and functional thru all of TT's updates I didn't use any of theirs code.
It means that I can't tell when your queue is fully loaded and I can't let the my code waiting for too long because a small queue loads really fast.
I'll look in some eventsListeners to see if anything changed.

[s]

**Comment by theschles** [comment]
Thanks
