### ISSUE TITLE
Horribly slow

### ISSUE THREAD

**Issue by theschles** [gilbarbara/Turntable.fm-Playlists#14]
Ok, I admit I have a lot of songs.  Screenshot of stats: http://www.flickr.com/photos/66524440@N08/6185504903/

TT.FM rooms take FOREVER to load with the extension enabled.  It is my ONLY TT.FM extension currently enabled.  I do use the Auto-Bop script, but do not enable it until after I can see the room's page is fully loaded.

Delays include watching a slowed down visual of head bopping of other users (at times heads seem frozen mid-bop).  Typing characters into chat input field extremely delayed.

**Comment by theschles** [comment]
Example video: http://www.youtube.com/watch?v=7tco2D7TVCI

**Comment by gilbarbara** [comment]
Hey theschles how are you?
Sorry about the delay..

I have 1500 songs in my queue and TT takes about 30-40 seconds to load even with the Playlist extension off. Have you timed the load with and without?

Also TT Extended can be very slow on big queues because it loop thru all your songs to add the tag icon. TT Playlists has an indicator option in settings but it is definitely too slow.

Let me know.

[s]

**Comment by theschles** [comment]
Video: http://www.youtube.com/watch?v=F6FHyDO-sbw

That's with 1401 songs in queue and 322 songs in playlists

**Comment by gilbarbara** [comment]
Hehe. It was even faster with the extension enabled! :)

blame TT!

**Comment by theschles** [comment]
Yep.  I guess I do have to blame TT...
