### ISSUE TITLE
Playlist window is blank

### ISSUE THREAD

**Issue by gruvmyster01** [gilbarbara/Turntable.fm-Playlists#24]
After the most recent update by TT on 08/16/2012 my playlist window appears blank.  I can still see all 30 of my playlists listed, and the total # of songs for each but no matter which one is selected the window remains blank.  I tried restoring my songs but that doesn't appear to be the case.  On the Info window I notice that it all stats show normally except "songs in your queue" shows as 0 when I have 1,798 songs in my queue.

**Comment by JaNoll** [comment]
Same issue here. Is there any fix?

**Comment by gruvmyster01** [comment]
Not that I know of yet... Looking into it. 

Sent from my Android Powered Device on the Now Network

----- Reply message -----

**Comment by mgretzigner** [comment]
Having the same issue. All my playlists are there with the number of tracks, but just whitespace in the box.
Running on a mac OSX 10.5.8

**Comment by mgretzigner** [comment]
Also, I tried making a new playlist. Was unable to drag songs in, and now cannot access the other playlists from the drop menu. 
:(

**Comment by gilbarbara** [comment]
hey!
Yeah, I can confirm that isn't working.
Turntable have made big changes in their code and my current approach won't work anymore.
I've managed to load the songs in the playlist but the play/top buttons aren't working.
:/

**Comment by BrendanMiller** [comment]
Any updates??

**Comment by Psykoral** [comment]
Had the same issue for a few days, Playlist would load but no songs present. As of today though, the Playlist isn't even showing up at all. Sounds like you're working on a fix, just wanted to throw in this tidbit of "not loading at all" now, in case it changes plans. Thanks for all the support!

This is the console.log for the event, might help:

Denying load of chrome-extension://eimhdmlhdgmboegnmecdnfbmdmhdoool/js/playlists.js?v=0.8316906078252941. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by web pages.

**Comment by gilbarbara** [comment]
https://github.com/gilbarbara/Turntable.fm-Playlists/issues/26
